const bank={nilai:[
['Nilai angka 7 pada 7.245 adalah ...',['7','70','700','7.000'],'7.000','Angka 7 pada 7.245 berada di tempat ribuan, jadi nilainya = 7 × 1.000 = 7.000.'],
['Angka 6 pada bilangan 3.684 menempati tempat ...',['satuan','puluhan','ratusan','ribuan'],'ratusan','3.684 = 3 ribuan + 6 ratusan + 8 puluhan + 4 satuan, sehingga angka 6 menempati tempat ratusan.'],
['Urutan dari terkecil: 2.140, 2.014, 2.401 adalah ...',['2.014, 2.140, 2.401','2.401, 2.140, 2.014','2.140, 2.014, 2.401','2.014, 2.401, 2.140'],'2.014, 2.140, 2.401','Ketiganya sama-sama 2 ribuan, jadi bandingkan angka ratusannya: 2.014 (0 ratusan) < 2.140 (1 ratusan) < 2.401 (4 ratusan).'],
['Bentuk panjang dari 5.306 adalah ...',['5.000 + 300 + 6','5.000 + 30 + 6','500 + 300 + 6','5.000 + 306'],'5.000 + 300 + 6','5.306 = 5 ribuan + 3 ratusan + 0 puluhan + 6 satuan = 5.000 + 300 + 0 + 6, ditulis 5.000 + 300 + 6.']],operasi:[
['2.345 + 1.245 = ...',['3.480','3.590','3.690','3.700'],'3.590','2.345 + 1.245 = 3.590.'],['4.800 - 1.275 = ...',['3.425','3.525','3.625','3.725'],'3.525','4.800 - 1.275 = 3.525.'],['3.400 + 2.750 = ...',['6.050','6.150','6.250','5.150'],'6.150','3.400 + 2.750 = 6.150.'],['7.500 - 2.350 = ...',['5.050','5.150','5.250','4.150'],'5.150','7.500 - 2.350 = 5.150.']],perkalian:[
['234 × 3 = ...',['612','702','704','724'],'702','234 × 3 = 702.'],['125 × 4 = ...',['450','500','525','600'],'500','125 × 4 = 500.'],['756 ÷ 3 = ...',['242','252','262','272'],'252','756 ÷ 3 = 252, karena 252 × 3 = 756.'],['423 ÷ 3 = ...',['131','141','151','161'],'141','423 ÷ 3 = 141, karena 141 × 3 = 423.']],faktor:[
['Kelipatan 6 yang benar adalah ...',['6, 12, 18, 24','5, 10, 15, 20','7, 14, 21, 28','8, 16, 24, 32'],'6, 12, 18, 24','Kelipatan 6 didapat dari 6×1, 6×2, 6×3, 6×4, ... = 6, 12, 18, 24, ...'],['Faktor dari 12 adalah ...',['1, 2, 3, 4, 6, 12','1, 2, 4, 8','2, 4, 6, 8','1, 3, 6, 9'],'1, 2, 3, 4, 6, 12','Faktor 12 adalah bilangan yang habis membagi 12, yaitu 1, 2, 3, 4, 6, dan 12.'],['Bilangan yang merupakan kelipatan 7 adalah ...',['12','14','16','18'],'14','14 = 7 × 2, jadi 14 adalah kelipatan 7. Sedangkan 12, 16, dan 18 tidak habis dibagi 7.'],['Faktor terbesar dari 18 adalah ...',['6','9','12','18'],'18','Faktor dari 18 adalah 1, 2, 3, 6, 9, dan 18. Faktor terbesarnya adalah 18 itu sendiri.']]};

const $=id=>document.getElementById(id), shuffle=a=>[...a].sort(()=>Math.random()-.5), rand=(min,max)=>Math.floor(Math.random()*(max-min+1))+min;
const topicNames={all:'Semua Materi',nilai:'Nilai Tempat',operasi:'Operasi Hitung',perkalian:'Perkalian & Pembagian',faktor:'Kelipatan & Faktor'};
let topic='all',questions=[],index=0,score=0,chosen=false;

function format(n){return n.toLocaleString('id-ID')}
function choices(correct,make){let values=new Set([format(correct)]);while(values.size<4)values.add(format(make()));return shuffle([...values])}
function generatedNilai(){let places=['satuan','puluhan','ratusan','ribuan'],n,digits,pos,digit;do{n=rand(1000,9999);digits=String(n).padStart(4,'0');pos=rand(0,3);digit=digits[3-pos]}while(digits.split('').filter(d=>d===digit).length>1);let value=Number(digit)*10**pos,explanation=`${format(n)} = ${digits[0]} ribuan + ${digits[1]} ratusan + ${digits[2]} puluhan + ${digits[3]} satuan. Angka ${digit} menempati tempat ${places[pos]} (nilainya ${digit} × ${format(10**pos)} = ${format(value)}).`;return [`Angka ${digit} pada bilangan ${format(n)} menempati tempat ...`,places.map(x=>x),places[pos],explanation]}
function generatedOperasi(){let a=rand(100,7000),b=rand(100,999),add=Math.random()<.5;if(!add&&b>a)[a,b]=[b,a];let answer=add?a+b:a-b,explanation=`${format(a)} ${add?'+':'-'} ${format(b)} = ${format(answer)}.`;return [`${format(a)} ${add?'+':'-'} ${format(b)} = ...`,choices(answer,()=>Math.max(0,answer+rand(-500,500))),format(answer),explanation]}
function generatedKali(){let divisor=rand(2,9),answer=rand(20,333)*divisor,three=answer/divisor;let multiply=Math.random()<.5;if(multiply){let a=rand(100,999),b=rand(2,9);return [`${a} × ${b} = ...`,choices(a*b,()=>rand(100,9999)),format(a*b),`${a} × ${b} = ${format(a*b)}.`]}return [`${format(answer)} ÷ ${divisor} = ...`,choices(three,()=>rand(20,999)),format(three),`${format(answer)} ÷ ${divisor} = ${format(three)}, karena ${format(three)} × ${divisor} = ${format(answer)}.`]}
function factors(n){let a=[];for(let i=1;i<=n;i++)if(n%i===0)a.push(i);return a}
function generatedFaktor(){let n=rand(4,30),isFactor=Math.random()<.5;if(isFactor){let fs=factors(n),correct=fs[rand(0,fs.length-1)],opts=new Set([correct]);while(opts.size<4){let candidate=rand(2,30);if(!fs.includes(candidate))opts.add(candidate)}return [`Manakah yang merupakan faktor dari ${n}?`,shuffle([...opts]).map(String),String(correct),`Faktor dari ${n} adalah ${fs.join(', ')}. Angka ${correct} termasuk faktor karena ${n} ÷ ${correct} = ${n/correct} (habis dibagi tanpa sisa).`]}let k=rand(2,10),correct=k*rand(2,10);return [`Manakah yang merupakan kelipatan ${k}?`,choices(correct,()=>rand(2,60)),format(correct),`${format(correct)} adalah kelipatan ${k} karena ${format(correct)} = ${k} × ${correct/k}.`]}
function generateQuestion(key){if(key==='nilai')return generatedNilai();if(key==='operasi')return generatedOperasi();if(key==='perkalian')return generatedKali();return generatedFaktor()}
function makeQuestions(){let keys=topic==='all'?Object.keys(bank):[topic],count=Number($('question-count').value),result=[];for(let i=0;i<count;i++){let key=keys[i%keys.length];result.push(Math.random()<.85?generateQuestion(key):bank[key][rand(0,bank[key].length-1)])}return shuffle(result)}

document.querySelectorAll('.topic').forEach(b=>b.onclick=()=>{document.querySelectorAll('.topic').forEach(x=>x.classList.remove('active'));b.classList.add('active');topic=b.dataset.topic});
function start(){questions=makeQuestions();index=0;score=0;$('home').classList.add('hidden');$('result').classList.add('hidden');$('quiz').classList.remove('hidden');show()}
function show(){chosen=false;let q=questions[index];$('counter').textContent=`Soal ${index+1} dari ${questions.length}`;$('points').textContent=`${score} poin`;$('progress-bar').style.width=`${index/questions.length*100}%`;$('question-number').textContent=`PERTANYAAN ${index+1}`;$('question').textContent=q[0];$('explanation').classList.add('hidden');$('next').disabled=true;$('next').textContent='Pilih Jawaban';$('answers').innerHTML='';shuffle(q[1]).forEach(answer=>{let b=document.createElement('button');b.className='answer';b.textContent=answer;b.onclick=()=>answerQuestion(b,answer,q);$('answers').appendChild(b)})}
function answerQuestion(button,answer,q){if(chosen)return;chosen=true;let correct=String(answer)===String(q[2]);if(correct)score++;document.querySelectorAll('.answer').forEach(b=>{b.disabled=true;if(String(b.textContent)===String(q[2]))b.classList.add('correct')});if(!correct)button.classList.add('wrong');$('points').textContent=`${score} poin`;let status=correct?'✅ Benar! Hebat!':'💡 Belum tepat. Jawaban yang benar adalah '+q[2]+'.';$('explanation').innerHTML=`<strong>${status}</strong><br>${q[3]}`;$('explanation').classList.remove('hidden');$('next').disabled=false;$('next').textContent=index===questions.length-1?'Lihat Hasil':'Soal Berikutnya'}
function next(){if(!chosen)return;if(++index<questions.length)show();else finish()}
function finish(){$('quiz').classList.add('hidden');$('result').classList.remove('hidden');$('score').textContent=`${score}/${questions.length}`;let p=score/questions.length*100;$('message').textContent=p>=80?'Luar biasa! Kamu sangat hebat! 🎉':p>=60?'Bagus! Terus berlatih agar semakin pintar! 😊':'Tetap semangat! Coba lagi dan pelajari materi dengan tekun! 💪'}
$('start').onclick=start;$('next').onclick=next;$('again').onclick=start;$('choose').onclick=()=>{$('result').classList.add('hidden');$('home').classList.remove('hidden')};$('quit').onclick=()=>{$('quiz').classList.add('hidden');$('home').classList.remove('hidden')};
